### ISSUE TITLE
release for ROS Kinetic

### ISSUE THREAD

**Issue by robotpilot** [AravindaDP/humanoid_navigation#5]
I think SBPL(Search-Based Planning Library) is an important dependency SW for releasing the humanoid_navigation package on ROS Kinetic. So I released SBPL as the binary package for ROS Kinetic. (https://github.com/ros-gbp/sbpl-release/issues/2) This SBPL will sync this week on Tuesday. (https://github.com/ros/rosdistro/pull/17302)

Do you plan to release for the ROS Kinetic version?

**Comment by AravindaDP** [comment]
@robotpilot thanks for getting SBPL released on Kinetic.
I was bit busy lately so couldn't put much attention after initial release. I see there have been few updates on the ahornung/humanoid_navigation which I would like to sync up before planning a release.
(Alternatively I might ask @ahornung to get me collaborative access so that I could directly work over the original repo for making it release ready)
Having said that I cannot guarantee a time line on a release date. If you like to give me a helping hand I would greatly appreciate it.

**Comment by robotpilot** [comment]
@AravindaDP 
Thank you for your reply. Now that I think about it again, you and I did a similar story a year ago. https://github.com/ahornung/humanoid_navigation/issues/14 and https://github.com/ros/rosdistro/pull/12555 :) I hope to continue this project, so I forked your rep at https://github.com/ROBOTIS-GIT/humanoid_navigation. If you're busy, Is it okay if I release humanoid_navigation package on ROS Kinetic?

**Comment by robotpilot** [comment]
@AravindaDP If you allow, I would like to include this package in sync with the next ROS Kinect. :)

**Comment by robotpilot** [comment]
Hi, @AravindaDP 
The author(Armin Hornung) of humanoid_navigation package seems to have allowed release and merge.
https://github.com/ahornung/humanoid_navigation/issues/14
So, I forked your repo and merged with bug fixes of original repo(https://github.com/ahornung/humanoid_navigation/pull/17) and ready for release on ROS Kinetic (https://github.com/ROBOTIS-GIT/humanoid_navigation/network).
I want to know your opinion or plan. If you allow, I hope to be a maintainer of this package.

**Comment by AravindaDP** [comment]
@robotpilot 
Sorry for the delayed response. if you have taken my changes I had done over a year ago. you should be good to go with a release on kinetic if you want to speed it up.
I'll be doing a new indigo release based on changes merged to ahornung/humanoid_navigation. Then I'll think of accepting any other PR from others.
If you wish to make a kinetic release based on either from my repo or yours no worries. For indigo only I think it would be convenient to release from mine.
My policy upto now was only to release based on ahornung/humanoid_navigation since my knowledge on actual implementation is limited to evaluate any PR. Do you consider yourself proficient enough on actual implementation by now?

**Comment by robotpilot** [comment]
Hi @AravindaDP 
I have been creating and managing various packages over the past two years. Currently, it manages more than 140 packages like the link below.
- http://wiki.ros.org/ROBOTIS

The [humanoid_navigation](http://wiki.ros.org/humanoid_navigation) package you managed was closely related to the humanoid([OP3](http://wiki.ros.org/robotis_op3) and [THORMANG3](http://wiki.ros.org/thormang3_mpc)) we provide. I want to manage this package for Kinect, Melodic. Because I actually use humanoid_navigation and I have about 20 releases of packages that depend on humanoid_navigation. After the release of the humanoid_navigation package, I will release these packages as well.
- http://wiki.ros.org/robotis_op3
- http://wiki.ros.org/thormang3_mpc

Thanks for your understanding and I will release the Kinect version this week.
